# Generated by Django 5.0.6 on 2025-08-11 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('farmer_name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=100)),
                ('governorate', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('crop_type', models.CharField(blank=True, max_length=150)),
                ('water_source', models.CharField(blank=True, max_length=150)),
                ('irrigation_system_type', models.CharField(blank=True, max_length=150)),
                ('distribution_uniformity_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.site')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
